apiVersion: 1

datasources:
  # Local Prometheus — scrapes AI agent + cart-api via ALB
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-local:9090
    isDefault: true
    editable: true

  # Remote Prometheus on ECS — for ECS-side metrics
  - name: Prometheus-ECS
    type: prometheus
    access: proxy
    url: http://cs6650-final-prom-nlb-f1dc54052fdf8f2e.elb.us-west-2.amazonaws.com:9090
    editable: true
